trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
    npm run test
    echo 'The push refers to repository [dockerhub.com/test17] nodefun-2dfdb03b: digest: sha256:f0a1d9c052196423590a8ab6f8ad4ffaba69b85425595ea27a45cae47c4a1257 size: 59791'
    echo 'The push refers to repository [dockerhub.com/test27] nodefun-2dfdb03c: digest: sha256:f0a1d9c052196423590a8ab6f8ad4ffaba69b85425595ea27a45cae47c4a1258 size: 59802'
  displayName: 'npm install and build'